### ISSUE TITLE
Release Candidate Checklist

### ISSUE THREAD

**Issue by lucascbeyeler** [lucascbeyeler/zmbackup#51]
##### ISSUE TYPE
- Checklist

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2.0 Release Candidate
- Zimbra Version: 8.7.11
- Linux Distribution & Version: Ubuntu & CentOS

##### SUMMARY
Bellow there are all the bugs found during the tests and that will be needed to fix before the next release.

- [x] Zmbackup is deleting lock file if you run a second time - should keep until the first time is running;
- [x] install.sh don't remove the zmbackup.cron if --remove is used;
- [x] Zmbackup -r is not working if you don't inform the restore type;
- [x] The message "preserve backup storage" is jumping a line;
- [x] Asked by saschadd: include all the backup routines inside zmbackup.cron;
- [x] Incremental backup should be doing a full backup instead when there is no full backup;
- [x] Migration should only run if the user change the option inside zmbackup.conf;
- [x] Database is locked for some reason;
- [x] Incremental is not running Full backup at first;
- [x] Mailbox don't count correctly how much accounts are backed up when try to send the e-mail;
- [x] Reported by Germán I. Paul: Zmbackup does not execute the backup routine inside CentOS;
- [x] Migrate should run only if Zmbackup is not running;
- [x] Zmbackup wasn't removing all the files after a routine;
- [x] Migration is broken;
- [x] Zmbackup computing wrong size in SQLITE3.

**Comment by lucascbeyeler** [comment]
All fixed! Releasing the Release Candidate 1 and return to the tests.
